# Generated by Django 3.1.1 on 2020-11-27 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0004_auto_20201127_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
