# Generated by Django 3.1.1 on 2020-11-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0005_auto_20201127_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_breeder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
