# Generated by Django 3.1.1 on 2020-11-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0006_user_is_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_breeder',
            field=models.BooleanField(default=False),
        ),
    ]
