# Generated by Django 3.1.1 on 2020-11-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0007_auto_20201127_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='review',
        ),
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewes', to='puppysearch.review'),
        ),
    ]
