# Generated by Django 3.1.1 on 2020-11-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0009_auto_20201128_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='review',
        ),
    ]
