# Generated by Django 3.1.1 on 2020-11-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppysearch', '0011_auto_20201128_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name_plural': 'colors'},
        ),
    ]
